services:
  spring-cloud-gateway:
    image: ghcr.io/samitkumarpatel/spring-cloud-gateway:261020242024
    volumes:
      - ./config:/usr/config
    environment:
      - JAVA_TOOL_OPTIONS="-Dreactor.netty.http.server.accessLogEnabled=true"
      - spring.config.import=/usr/config/application.yml
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.role == manager
    ports:
      - target: 9000
        published: 9000
        mode: host
  
  kong:
    image: kong/kong-gateway:3.8
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/declarative/kong.yml"
    ports:
      - target: 8000
        published: 8000
        mode: host
      - target: 8443
        published: 8443
        mode: host
      - target: 8001
        published: 8001
        mode: host
      - target: 8444
        published: 8444
        mode: host
    volumes:
      - ./config/kong.yml:/kong/declarative/kong.yml
  
  nginx:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M

  db:
    image: 'postgres:14.1-alpine'
    environment:
      - 'POSTGRES_DB=todo'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.role == manager

  todo:
    image: ghcr.io/samitkumarpatel/todo:261020242011
    restart: on-failure
    depends_on:
      - "db"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.role == manager
    environment:
      spring.datasource.url: 'jdbc:postgresql://db:5432/todo'
      spring.datasource.username: 'user'
      spring.datasource.password: 'secret'
      spring.flyway.enabled: 'true'