services:
  spring-cloud-gateway:
    image: ghcr.io/samitkumarpatel/spring-cloud-gateway:main
    volumes:
      - ./gateway-config:/usr/data
    environment:
      - JAVA_TOOL_OPTIONS="-Dreactor.netty.http.server.accessLogEnabled=true"
      - spring.config.location=/usr/data/
    ports:
      - target: 8080
        published: 8000
        mode: host
  
  nginx:
    image: nginx
    # ports:
    #   - target: 80
    #     published: 80
    #     mode: host
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro

  postgres-db:
    image: 'postgres:14.1-alpine'
    environment:
      - 'POSTGRES_DB=todo'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.role == manager

  todo:
    image: ghcr.io/samitkumarpatel/todo:201020242046
    restart: on-failure
    depends_on:
      - "db"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.role == manager
    environment:
      spring.datasource.url: 'jdbc:postgresql://postgres-db:5432/todo'
      spring.datasource.username: 'user'
      spring.datasource.password: 'secret'
      spring.flyway.enabled: 'true'
    # ports:
    # - target: 8080
    #   published: 8080
    #   mode: host
