_format_version: "3.0"
services:
  - name: nginx-service
    url: http://nginx:80
    routes:
      - name: nginx-route
        paths:
          - /nginx
        strip_path: true

  - name: todo-web-service
    url: http://todo:8080
    routes:
      - name: todo-web-route
        paths:
          - /todo
        strip_path: true

  - name: todo-service
    url: http://todo:8080
    routes:
      - name: todo-route
        paths:
          - /todo/
        strip_path: false

      
