---
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: todo
          uri: http://todo:8080
          predicates:
            - Path=/todo/**
          filters:
            - SetPath=/todo
        
        - id: nginx
          uri: http://nginx:80
          predicates:
            - Path=/nginx
          filters:
            - SetPath=/

